# Generated by Django 4.1.2 on 2022-11-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryJewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('instagram', models.CharField(max_length=32)),
                ('whatsapp', models.BooleanField(default=False)),
                ('mobile', models.CharField(max_length=16)),
                ('house_office', models.CharField(max_length=16)),
                ('image_contact', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('address', models.CharField(max_length=128)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_gold', models.FloatField()),
                ('parallel_dollar', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('genre', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=8)),
                ('weight', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('heigth', models.FloatField()),
                ('thickness', models.FloatField()),
                ('image_jewel', models.ImageField(upload_to='jewelry/images/%Y/%m/%d/')),
                ('note', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jewelry.categoryjewelry')),
            ],
        ),
        migrations.CreateModel(
            name='TypesMetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TypesPearls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TypesStones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('size', models.FloatField()),
                ('carat', models.FloatField()),
                ('value', models.FloatField()),
                ('jewelry_id', models.ManyToManyField(to='jewelry.jewelry')),
                ('stone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jewelry.typesstones')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.CharField(choices=[('Metal', 'Metal'), ('Stones', 'Stones'), ('Pearls', 'Pearls')], max_length=8)),
                ('provider', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('jewelry_id', models.ManyToManyField(to='jewelry.jewelry')),
            ],
        ),
        migrations.CreateModel(
            name='Pearls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('size', models.FloatField()),
                ('color', models.CharField(max_length=16)),
                ('value', models.FloatField()),
                ('jewelry_id', models.ManyToManyField(to='jewelry.jewelry')),
                ('pearl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jewelry.typespearls')),
            ],
        ),
        migrations.CreateModel(
            name='ModelsJewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jewelry.categoryjewelry')),
            ],
        ),
        migrations.AddField(
            model_name='jewelry',
            name='metal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jewelry.typesmetals'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jewelry.modelsjewelry'),
        ),
    ]
