# Generated by Django 4.1.2 on 2022-11-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='company',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='image_contact',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='fine_gold',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='parallel_dollar',
            field=models.FloatField(blank=True),
        ),
    ]
