# Generated by Django 4.1.2 on 2022-11-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_alter_contacts_address_alter_contacts_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='image_contact',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='fine_gold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='parallel_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
